#-*- coding: utf-8 -*-
plandata = [
["id_proyecto","descripcion","faseDevOps","PuntosH","fechaInicio","fechaFin","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","20/11/2020","25/08/2021","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","05/11/2021","10/07/2022","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],

]

coddata = [
["id_proyecto","descripcion","faseDevOps","Defectos","fechaInicio","fechaFin","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","20/11/2020","25/08/2021","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","05/11/2021","10/07/2022","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],

]
consdata = [
["id_proyecto","descripcion","faseDevOps","CompilacionExitosa","fechaIni","fechaFin","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","20/11/2020","25/08/2021","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","05/11/2021","10/07/2022","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],

]
prudata = [
["id_proyecto","descripcion","faseDevOps","PruebasExitosa","fecha","fechaFin","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","10/01/2021","05/09/2022","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","07/01/2021","25/08/2021","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","10/03/2022","10/07/2022","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],
]
landata = [
["id_proyecto","descripcion","faseDevOps","NumLan","fechaIni","fechaFin","Horas","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","10/01/2021","05/09/2022","4","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","9","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","2","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","6","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","10","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","7","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","4","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","2","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","07/01/2021","25/08/2021","2","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","6","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","6 ","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","20","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","0","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","1","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","10/03/2022","10/07/2022","4","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","12","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","2","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","15","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","10","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","4","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","16","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","3","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","3","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","0","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","10","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","1","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","15","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","9","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","13","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","7","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","0","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","3","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],

]
dspdata= [
["id_proyecto","descripcion","faseDevOps","NumDespli","fechaIni","fechaFin","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","paneacion","2","10/01/2021","05/09/2022","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","07/01/2021","25/08/2021","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","10/03/2022","10/07/2022","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],
 ]
opdata = [
["id_proyecto","descripcion","faseDevOps","Errores","fechaIni","fechaFin","TiempoDet","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","10/01/2021","05/09/2022","4","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","9","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","2","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","6","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","10","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","7","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","4","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","2","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","07/01/2021","25/08/2021","2","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","6","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","6 ","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","20","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","0","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","1","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","10/03/2022","10/07/2022","4","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","12","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","2","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","15","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","10","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","4","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","16","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","3","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","3","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","0","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","10","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","1","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","15","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","9","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","13","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","7","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","0","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","3","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],

]
mondata = [
["id_proyecto","descripcion","faseDevOps","TiempoRec","fechaIni","fechaFin","Recu","observaciones","entregable","responsable"],
["HeladosXochi","se requiere un punto de venta","planeacion","2","10/01/2021","05/09/2022","4","se require mas analisis","doc de analisis","cesar merino"],
["Dulces Sandy","se requiere sistema de almacen","Desarrollo","7","03/03/2018","05/05/2020","9","se require mas analisis","doc de casos de prueba","Luis Flores"],
["Autos Vaca","sistema de facturacion","lanzamiento","4","22/04/2021","05/09/2022","2","se require mas analisis","doc de analisis","Enrique nunes"],
["Joyeria Ana","se requiere un punto de venta","pruebas","5","22/04/2021","05/09/2022","6","se require mas analisis","historias de usuario","Jonatan cordero"],
["Farmacia Simon","se requiere un punto de venta","Monitoreo","8","22/04/2021","05/09/2022","10","se require mas analisis","doc de analisis","miguel romero"],
["Inmobiliaria Torres","sistema de gestión de propiedades","Desarrollo","3","10/10/2020","15/07/2021","7","Requiere optimización de rendimiento","Informe de rendimiento","Sara Martínez"],
["Viajes Express","plataforma de reserva de viajes","Despliegue","6","15/06/2019","20/12/2020","4","Se requiere implementar mejoras de seguridad","Informe de auditoría de seguridad","Carlos Sánchez"],
["Librería Central","sistema de gestión de inventario","Mantenimiento","1","05/03/2020","10/11/2021","2","Necesita actualización de bibliotecas","Registro de actualizaciones","María López"],
["Restaurante El Sazón","sistema de pedidos en línea","Monitoreo","2","07/01/2021","25/08/2021","2","Se necesita mejorar la monitorización de la aplicación móvil","Informe de monitorización","Javier Rodríguez"],
["Academia Virtual","plataforma de aprendizaje en línea","Pruebas","4","08/07/2021","15/04/2022","6","Se requieren más pruebas de integración","Registro de pruebas de integración","Laura Pérez"],
["Ferretería Martínez","sistema de gestión de inventario","Desarrollo","3","12/09/2019","18/05/2020","6 ","Se necesitan más especificaciones de requisitos","Documento de especificaciones","Pedro Gómez"],
["Cine 360","plataforma de streaming de películas","Desarrollo","5","30/04/2020","05/09/2021","20","Se requiere optimización de la velocidad de carga","Informe de optimización de rendimiento","Ana Soto"],
["Gimnasio FitZone","sistema de gestión de socios","Despliegue","0","15/03/2022","20/10/2023","0","Se requiere configurar el balanceo de carga","Configuración de balanceo de carga","Juan Hernández"],
["Tienda de Ropa Fashionista","plataforma de comercio electrónico","Implementación","2","10/08/2020","15/05/2021","1","Necesita actualización de la interfaz de usuario","Informe de actualización de interfaz de usuario","Elena Díaz"],
["Cafetería Aromas","sistema de pedidos en línea","Desarrollo","4","10/03/2022","10/07/2022","4","Requiere refactorización del código","Informe de refactorización","David Pérez"],
["Empresa de Logística TransRápido","sistema de gestión de flotas","Pruebas","6","22/06/2019","25/01/2021","12","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Sandra García"],
["Clínica Médica SaludPlus","sistema de historias clínicas electrónicas","Mantenimiento","1","15/09/2020","20/04/2022","2","Necesita parches de seguridad","Registro de parches de seguridad","Roberto Martínez"],
["Agencia de Publicidad Creativa","plataforma de gestión de campañas","Monitoreo","3","20/03/2021","25/10/2022","15","Se requiere mejorar la monitorización de la carga del servidor","Informe de monitorización de carga","Patricia Ruiz"],
["Estudio de Diseño Arte y Estilo","sistema de gestión de proyectos","Implementación","5","12/12/2019","15/07/2021","10","Necesita integración con herramientas de gestión de documentos","Informe de integración de herramientas","Ricardo Hernández"],
["Plataforma de Juegos Online GameLand","plataforma de juegos en línea","Desarrollo","2","05/07/2021","10/02/2023","4","Requiere más pruebas de seguridad","Informe de pruebas de seguridad","Jorge Ramírez"],
["Consultora de Recursos Humanos HRConsulting","sistema de gestión de talento","Despliegue","4","30/10/2018","05/05/2020","16","Necesita configuración de escalabilidad","Informe de escalabilidad","Carmen García"],
["Escuela de Idiomas Polyglot","plataforma de aprendizaje de idiomas en línea","Pruebas","1","22/08/2021","25/03/2022","3","Se requiere más automatización de pruebas","Informe de automatización de pruebas","Francisco Torres"],
["Startup Innovadora TechStart","plataforma de colaboración empresarial","Desarrollo","3","10/06/2019","15/01/2021","3","Requiere más especificaciones de diseño","Documento de diseño","Marta Rodríguez"],
["Empresa de Seguros SegurPlus","sistema de gestión de pólizas","Implementación","0","18/04/2022","20/11/2023","0","Necesita configuración de monitorización de logs","Informe de monitorización de logs","Diego Martín"],
["Compañía de Viajes Turísticos TravelMax","plataforma de reservas de viajes","Despliegue","2","25/02/2020","30/09/2021","10","Requiere más pruebas de compatibilidad con navegadores","Informe de pruebas de compatibilidad","Adriana Sánchez"],
["Empresa de Telecomunicaciones TeleCom","sistema de gestión de clientes","Mantenimiento","1","10/11/2020","15/06/2022","1","Necesita actualización de la base de datos","Informe de actualización de base de datos","Antonio Pérez"],
["Tienda de Electrodomésticos ElectroMax","plataforma de comercio electrónico","Pruebas","5","08/05/2021","10/12/2022","15","Se requieren más pruebas de rendimiento","Informe de pruebas de rendimiento","Lorena Gómez"],
["Empresa de Desarrollo de Software TechSoft","sistema de seguimiento de proyectos","Desarrollo","4","15/07/2019","20/02/2021","9","Necesita refactorización de código","Informe de refactorización de código","Gabriel López"],
["Hotel Paradise","sistema de reservas y gestión de hotel","Desarrollo","3","20/03/2020","25/10/2021","13","Requiere más pruebas de integración","Informe de pruebas de integración","Paula Martínez"],
["Empresa de Consultoría Estratégica StrategyConsult","plataforma de análisis de datos","Implementación","2","05/09/2020","10/04/2022","7","Necesita integración con API de terceros","Informe de integración con API","Arturo Sánchez"],
["Tienda de Artículos Deportivos SportMax","plataforma de comercio electrónico","Despliegue","0","22/01/2022","25/08/2023","0","Se requiere configuración de CDN","Informe de configuración de CDN","Eduardo Gutiérrez"],
["Startup Innovadora TechInnovate","plataforma de gestión de proyectos","Pruebas","3","18/08/2021","20/03/2022","3","Requiere más pruebas de usabilidad","Informe de pruebas de usabilidad","Ana García"],
]